### ISSUE TITLE
The future of Melee Light

### ISSUE THREAD

**Issue by wbobeirne** [schmooblidon/meleelight#1]
Hey Schmooblidon, huge fan of this project, and I'm really glad you've gone the open source route. I'm extremely interested in contributing, and I wanted to get a sense of where you see this project going, and what you want to work on (first, or at all.) Some things that I think would be extremely helpful to this project are:

* A proper dependency management / build system (I'm very fond of Webpack for this.)
* Some amount of testing, to make accepting PRs somewhat easier.
* A [github pages page](https://pages.github.com/) where this project can be played at.
* Figuring out how to deal with project versions, releases, etc.
* Setting up a slack / discord server or something, to discuss the project.
* Implementing a linter for code standards / catch easy errors (I'm a fan of ESLint for this.)

Sorry if the title of this issue is overly grandiose.

**Comment by Dickurt** [comment]
Another important question, I feel, is whether @schmooblidon has any poignant issues with the project that should be resolved. For example, I already saw an instance with 10 closing curly braces. And some files with over a thousand LOC, which could be split up. Once the current codebase is cleaner, later contributions will be made easier.

On a different note: TypeScript for this project would be amazing. I would love to do it, but there's no way I'd ever get around doing that.

**Comment by wbobeirne** [comment]
Yep, code clarity and standards will be huge for a project of this size. Some discussion of this moved over to Discord, but I've already started a webpack / babel / eslint conversion branch over here: https://github.com/wbobeirne/meleelight/tree/webpack It's off to a good start, but it'll be a while before I can convert over the entirety of the codebase. But once that's done, adding more tooling to the project (like Typescript) should be considerably easier.

**Comment by marceux** [comment]
@wbobeirne How can peeps such as myself join the Discord?

**Comment by wbobeirne** [comment]
It's over on the smashboards thread, but we should probably put it in the readme: https://discord.gg/qagFayt

**Comment by wbobeirne** [comment]
Closing this issue out in favor of smaller issues for individual tasks. General discussion of this project has moved over to the discord linked above.
