### ISSUE TITLE
Clipped Through Wall on Target Test 9

### ISSUE THREAD

**Issue by JohnnyUrosevic** [schmooblidon/meleelight#17]
Did a waveland onto the platform and clipped through the wall (getting a really fast record)

It was the wall to the right 2nd to last platform on the very left side of the stage

**Comment by JohnnyUrosevic** [comment]
http://prntscr.com/dnkszv

**Comment by sheaf** [comment]
I'm on this, don't worry.

**Comment by sheaf** [comment]
Fixed with the merge of the environmental collision changes in commit 669b2e6.
