### ISSUE TITLE
Shield VFX does not appear during match

### ISSUE THREAD

**Issue by sheaf** [schmooblidon/meleelight#38]
Since the `rafactor` branch merge, the shield vfx do not appear during a match, while they work just fine in the character select screen. Note that the shield break vfx do work as expected.

![shieldvfx_1](https://cloud.githubusercontent.com/assets/1297748/20764558/fb217338-b72e-11e6-8dca-bb82b60989b3.PNG)

![shieldvfx_2](https://cloud.githubusercontent.com/assets/1297748/20764559/fb2813e6-b72e-11e6-8392-50964a94ecf7.PNG)

I am not getting any errors in the console, but maybe someone adept at debugging can go through and see what is happening. 

This issue is happening on both Chrome and Firefox on my end, and with both meleelight.html and meleelightikd.html.

**Comment by nolram88** [comment]
looks like @schmooblidon got it in the last push
