### ISSUE TITLE
Text alignment not being reset in target test builder

### ISSUE THREAD

**Issue by sheaf** [schmooblidon/meleelight#77]
The text alignment is not reset to the left when testing a target test stage from the target test stage builder.

![target_builder_text_align](https://cloud.githubusercontent.com/assets/1297748/21080156/3783e2a8-bfa8-11e6-8d15-70381562a976.PNG)

**Comment by tatatat0** [comment]
fixed in https://github.com/schmooblidon/meleelight/pull/89
