### ISSUE TITLE
Incorrect quit combo checking

### ISSUE THREAD

**Issue by mastermark5** [schmooblidon/meleelight#82]
In main/main.js:643, we are checking to see if either player 1 or player 2 is holding down the traditional quit button combo: L+R+A+START. However, we are checking it like this:

`(tempBuffer[0].a || tempBuffer[1].a) && (tempBuffer[0].l || tempBuffer[1].l) && (tempBuffer[0].r || tempBuffer[1].r) && (tempBuffer[0].s || tempBuffer[1].s)` (

Is this really the intended logic? This checks either player 1 or player 2 happen to be holding any of these buttons. In actual Melee, the buttons are checked PER PLAYER as opposed to the logic being combined. With this logic, player 1 and player 2 can accidentally quit the game by playing the game legitimately, such as if player 1 were holding down A+R, and player 2 were holding down L+START.

Link to source: https://github.com/schmooblidon/meleelight/blob/master/src/main/main.js#L643

**Comment by sheaf** [comment]
That's not what's happening; the `[0]` and `[1]` refer to inputs on current frame (0) and previous frame (1), it's not a player number. This code is run separately for each player.

**Comment by mastermark5** [comment]
Sorry about that. I wasn't sure what was happening because tempBuffer isn't documented. Can we at least document this to make it more clear?

**Comment by sheaf** [comment]
I agree, some of that stuff could use a bit of clarifying.

**Comment by mastermark5** [comment]
Should we open an issue? Or possibly modify this one?

**Comment by sheaf** [comment]
See issue #83.

**Comment by mastermark5** [comment]
Awesome! I would love to start actually contributing to this repository and documentation would definitely help.
