### ISSUE TITLE
physics game crash

### ISSUE THREAD

**Issue by ocawa** [schmooblidon/meleelight#93]
was in the middle of a jab [picture here of the crash](http://imgur.com/a/52Ueq). Music and background animations still playing too

Sometimes happens with the variant "Cannot read property '0' of undefined" or something like that, but it's less often in my limited experience of playing.

```
Uncaught TypeError: Cannot read property 'x' of undefined
    at physics (physics.js:844)
    at update (main.js:908)
    at gameTick (main.js:1055)
```

**Comment by nolram88** [comment]
took care of this one recently.
