### ISSUE TITLE
server pvp CSS glitch

### ISSUE THREAD

**Issue by ocawa** [schmooblidon/meleelight#94]
Uncaught TypeError: Cannot read property 'length' of undefined
    at drawArrayPathCompress (render.js:49)
    at drawCSS (css.js:752)
    at renderTick (main.js:1166)

marth swings sword around seemingly randomly

**Comment by nolram88** [comment]
looks like ive dealt with this one. Could you check again?

**Comment by ocawa** [comment]
Ye sure, let me see if my testing partner is online

**Comment by nolram88** [comment]
I've made a ton of changes since this was opened.
